[package]
name = "minios"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
cc = "1.0" # cc 用来编译 AT&T 汇编

[profile.dev]
panic = "abort" # abort 表示内核不能 unwind

[profile.release]
panic = "abort"
